### PR TITLE
Resolve keybind conflict. Set WTHIT display to trigger

### PR DESCRIPTION
**Pull request by falseresync**

### CODE REVIEW

**Review by TheEpicBlock — APPROVED** [review]
This'd replace everybody's keybinds right? Better to do it now then I guess

**Comment by falseresync** [comment]
Unless people decline, it should

**Comment by deniz-blue** [comment]
since it's going to overwrite options.txt, we can also resolve some keybinds before we merge

just so we dont destroy everyone's keybinds twice...

example lines from my instance (idk about the wizcraft keybind)

```
lastServer:modfest.sleeping.town
joinedFirstServer:true
onboardAccessibility:false
key_key.wizcraft.tool_control:key.keyboard.c
key_key.saveToolbarActivator:key.keyboard.unknown
```

**Comment by falseresync** [comment]
could alternatively move axiom to `\` key, which is what i have

**Comment by deniz-blue** [comment]
keyboard layouts :c not everyone uses the same english one

`\` is not a key for me but `AltGr`+`*`

**Comment by sleepingdragoninn** [comment]
is there any particular reason that wizcraft should have the left alt canon bind when wthit affects user experience / screen clutter over the entire fest?

seems like wizcraft change spell could just as easily be c/v/b/g/r, or any other reasonably wasd-accessible key.

We do genuinely think that default-on toggle waila is a usability issue for players - modfest is a sensory overload as it is.

**Comment by falseresync** [comment]
Alt keybind is not a problem at all, C keybind or anything else really is just as fine.

It's the WTHIT settings that I dislike, for me it was the confusing decision that defeats the point of WTHIT for me personally and I disagree that it makes any big difference for the clutter

**Comment by sleepingdragoninn** [comment]
is it possible you play on a high resolution /low GUI scale? even tweaked to take up the smallest footprint possible (as I've done), the screen residency & text that changes sickeningly fast during regular gameplay has always been a problem for us, especially at fests with big bright builds and picturesigns and player nameplates in the mix.

**Comment by falseresync** [comment]
What you're describing seems like an accessibility issue, rather than a usability issue. If so, then it wouldn't be ideal to enable it by default, just like it wouldn't with many other accessibility features

**Comment by sleepingdragoninn** [comment]
just how accessible do you think it is to change the wthit settings for players who finds visiting modfest events overwhelming :P there's a reason the narrator is turned on when it's startup screen is shown.

**Comment by falseresync** [comment]
Well, I don't really care about WTHIT config, I just don't agree with your reasoning
If you really do believe it should be your way, I am not against having it that way
In the end all I really need is to have the keybind conflicts between WTHIT/Wizcraft/Axiom resolved to have a clear tutorial in my mod booth

**Comment by falseresync** [comment]
Already fixed

**Pull request closed without merging**
